site_name: Govcookiecutter Lite
repo_url: https://github.com/best-practice-and-impact/govcookiecutter-lite
repo_name: govcookiecutter-lite
nav:
  - Overview: 
    - Getting Started: index.md
    - More info: readme.md
  - created folder overview:
        - created folder structure: ./{{ cookiecutter.repo_name }}/docs_repo_README.md
  - Contributing:
    - Contributing Guide: CONTRIBUTING.md
    - Code of Conduct: CODE_OF_CONDUCT.md
    - Modifying Govcookiecutter-lite: ./contributing_guide/modify_govcookiecutter-lite.md
  - Development folder overview:
        - development: ./govcookiecutter_structure/docs_structure_README.md
        - docs: docs_README.md



theme:
  logo: "_static/af-logo.png"
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode


    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.path
    - navigation.sections
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      toc_depth: 2

plugins:
  - mkdocstrings

extra_css:
  - _static/mkdocs_custom.css