site_name: Govcookiecutter Lite
repo_url: https://github.com/best-practice-and-impact/govcookiecutter-lite
repo_name: govcookiecutter-lite
nav: 
  - Quick Start Guide: index.md
  - Detailed Summary: readme.md
  - Creation Prompts: created_project_structure/prompts.md
  - Created Folder Structure: created_project_structure/created_folder_structure.md
  - Contributing:
    - Contributing Guide: contributing/CONTRIBUTING.md
    - Code of Conduct: contributing/CODE_OF_CONDUCT.md
    - Modifying Govcookiecutter-lite: contributing/modify_govcookiecutter-lite.md
    - Development Folder Structure: contributing/docs_structure_README.md
    - Creating an Example Project: contributing/create_example.md
    - Hooks: contributing/hooks_api_reference.md
  - accessibility: accessibility.md




theme:
  logo: "_static/af-logo.png"
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode


    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.path
    - navigation.sections
    - toc.integrate
    - navigation.tabs
    - search.suggest
    - navigation.top
    - navigation.expand
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocstrings
  - search

extra_css:
  - _static/mkdocs_custom.css