name: govcookiecutter template build

on:
  push:
    branches:
      - main

jobs:
  template-build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: Fix R pre-commit hook issues with Windows
        os: [ ubuntu-latest] #, macos-latest ]
        python: [ 3.9, '3.12' ] #, 3.9, '3.10' ]

    steps:
      - name: Checkout the revision
        uses: actions/checkout@v4
        with:
          path: ga-govcookiecutter
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install cookiecutter
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            # TODO: Add pip alternative, as Ubuntu 20.04LTS not currently supported (June 2021)
            sudo apt-get install cookiecutter || pip install cookiecutter
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install cookiecutter
          elif [ "$RUNNER_OS" == "Windows" ]; then
            pip install cookiecutter
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi;
        shell: bash
      - name: Create project from govcookiecutter for this commit
        run: cookiecutter ga-govcookiecutter --no-input project_name=example
        shell: bash
      - name: Install requirements
        run: |
          cd example
          git init
          git add .
          pip install -U pip setuptools
          pip install -e .[dev]
        shell: bash
